# Versão antiga

# version: '3.4'
# services:
#   db:
#     image: mysql:5.7.22
#     volumes:
#     - db_data:/var/lib/mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: docker
#       MYSQL_USER: docker
#       MYSQL_PASSWORD: docker
#       MYSQL_DATABASE: wordpress

#   wordpress:
#     image: wordpress:latest
#     ports:
#       - 80:80
#     environment:
#       TZ: America/Sao_Paulo
#       WORDPRESS_DB_HOST: db:3306
#       WORDPRESS_DB_NAME: wordpress
#       WORDPRESS_DB_USER: root
#       WORDPRESS_DB_PASSWORD: docker

# volumes: 
#   db_data: {}

# Nova versão

version: '3.4'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --default_authentication_plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: wordpress
    ports:
      - 3308:3306

  wordpress:
    image: wordpress:latest
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html
    environment:
      TZ: America/Sao_Paulo
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: docker
    ports:
      - 80:80
